### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by GigaHierz** [GigaHierz/kkeerrnn#1]
- [x] menu points should have the same size

- [x] footer menu - mehr margin.... mehr mittig

- [x] blogpost preview background streifen rechts entfehrnen (wiederholung vom fotto (vll acuh max-zoom) oder bild länger ziehen

- [x] blogppost mehr abstand zum footer menu

- [x] 404. svg with proper font, size

- [x] search bar

- [x] such beiträge: stylen like hoempage

- [x] search for no results

- [x] no post limit per page

- [x] weißer balken zwischen blogpost& artikel für first child

- [x] add font

- [x] add datenschutz

- [x] add impressum
